apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
      - name: django-migrations
        image: nyuappsec/assign3:v0
        command: ["/bin/sh", "-c"]
        args: ['python3 manage.py makemigrations && python3 manage.py migrate']
        ports:
          - containerPort: 8000
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
             secretKeyRef:
                     name: mysql-login-secrets
                     key: MYSQL_ROOT_PASSWORD

          - name: MYSQL_DB
            value: GiftcardSiteDB
          
          - name: MYSQL_HOST
            value: mysql-service

          - name: ALLOWED_HOSTS
            value: "*,"

          - name: ADMIN_UNAME
            valueFrom:
              secretKeyRef:
                  name: admin-login-secrets
                  key: username

          - name: ADMIN_PASS
            valueFrom:
              secretKeyRef:
                  name: admin-login-secrets
                  key: password
        restartpolicy: Never
  backoffLimit: 4
